"""
Curated university & destination country knowledge base for the Ethos AI Counselor.

Focuses on destinations popular with Bangladeshi students (USA, UK, Canada, Australia,
Germany, Sweden, Malaysia). Includes minimum GPA cutoffs, English language requirements,
tuition & living cost estimates in local currency and BDT Lakhs, visa financial rules,
and scholarship/MOI options.
"""
from __future__ import annotations

from typing import Any

CURRENCY_RATES_TO_BDT: dict[str, float] = {
    "USD": 122.50,
    "GBP": 158.00,
    "CAD": 90.50,
    "AUD": 80.00,
    "EUR": 133.00,
    "SEK": 11.60,
    "MYR": 27.80,
}

COUNTRY_VISA_RULES: dict[str, dict[str, Any]] = {
    "Germany": {
        "blocked_account_eur": 11904,
        "estimated_solvency_bdt_lakh": 16.5,
        "solvency_summary_en": "Requires mandatory Blocked Account (€11,904) with Fintiba/Expatrio/Coracle.",
        "solvency_summary_bn": "জার্মান ভিসার জন্য ফিনটিবা বা এক্সপ্যাট্রিওতে €১১,৯০৪ ইউরোর ব্লকড অ্যাকাউন্ট বাধ্যতামূলক (প্রায় ১৬.৫ লাখ টাকা)।",
        "work_rights": "140 full days or 280 half days per year.",
        "study_gap_policy": "Strict. Study gap > 1 year requires formal employment proof and payslips.",
        "key_notes_en": "Most public universities have 0 tuition fee (only semester fee of €250-€400). High visa interview backlog in Dhaka VFS.",
        "key_notes_bn": "অধিকাংশ পাবলিক বিশ্ববিদ্যালয়ে কোনো টিউশন ফি নেই (শুধুমাত্র প্রতি সেমিস্টারে €২৫০-€৪০০ অ্যাডমিন ফি)। তবে ঢাকা ভিএফএসে অ্যাপয়েন্টমেন্ট পেতে দীর্ঘ সময় লাগে।",
    },
    "UK": {
        "living_cost_london_gbp_per_month": 1334,
        "living_cost_outer_gbp_per_month": 1023,
        "months_required": 9,
        "estimated_solvency_bdt_lakh": 28.0,
        "solvency_summary_en": "1st year tuition balance + 9 months living costs held for consecutive 28 days in recognized bank.",
        "solvency_summary_bn": "১ম বছরের বাকি টিউশন ফি + ৯ মাসের লিভিং কস্ট (লন্ডনের বাইরে প্রায় £৯,২০৭ পাউন্ড) একটানা ২৮ দিন অনুমোদিত ব্যাংকে থাকতে হবে।",
        "work_rights": "20 hours per week during term time, full-time during holidays.",
        "study_gap_policy": "Accepts 2-5 years gap if supported by continuous employment records and tax papers.",
        "key_notes_en": "Strict TB screening and credibility interview at VFS Dhaka. Graduate Route gives 2-year post-study work visa.",
        "key_notes_bn": "টিবি টেস্ট ও ক্রিডিবিলিটি ইন্টারভিউ দিতে হতে পারে। গ্র্যাজুয়েট রুটে ২ বছরের পোস্ট-স্টাডি ওয়ার্ক ভিসা (PSW) সুবিধা আছে।",
    },
    "USA": {
        "estimated_solvency_bdt_lakh": 38.0,
        "solvency_summary_en": "Must show liquid funds covering 1 full year I-20 expenses (Tuition + Living) + source of income for subsequent years.",
        "solvency_summary_bn": "I-20 তে উল্লেখিত ১ বছরের পুরো খরচ (টিউশন ও লিভিং) এবং পরবর্তী বছরগুলোর তহবিলের বিশ্বাসযোগ্য প্রমাণ (স্পন্সরশিপ/ইনকাম) দেখাতে হবে।",
        "work_rights": "On-campus 20 hours/week during session; CPT/OPT for field-related training.",
        "study_gap_policy": "Flexible on gap if genuinely justified, but Section 214(b) (immigrant intent) rejection rate is significant.",
        "key_notes_en": "F-1 visa interview at US Embassy Dhaka is decisive. Strong home ties and clear study plans are paramount.",
        "key_notes_bn": "মার্কিন দূতাবাসে ফেস-টু-ফেস ভিসা ইন্টারভিউতে কনভিন্স করা সবচেয়ে গুরুত্বপূর্ণ। পড়াশোনা শেষে দেশে ফেরার স্পষ্ট পরিকল্পনা থাকতে হবে।",
    },
    "Canada": {
        "gic_cad": 20635,
        "estimated_solvency_bdt_lakh": 32.0,
        "solvency_summary_en": "Guaranteed Investment Certificate (GIC) of $20,635 CAD + first year tuition paid receipt.",
        "solvency_summary_bn": "কানাডার জন্য $২০,৬৩৫ ক্যাড GIC ডিপোজিট এবং ১ম বছরের টিউশন ফি পরিশোধের রসিদ বাধ্যতামূলক।",
        "work_rights": "24 hours per week off-campus during academic semesters.",
        "study_gap_policy": "Allows gaps if substantiated with job experience; Canadian visa officers scrutinize dual-intent and study progression.",
        "key_notes_en": "Provincial Attestation Letter (PAL) quota limits apply. High visa standards on finances and tie-backs to Bangladesh.",
        "key_notes_bn": "বিশ্ববিদ্যালয় থেকে প্রভিন্সিয়াল অ্যাটেস্টেশন লেটার (PAL) দরকার হবে। ব্যাংক ব্যালেন্স ও ট্যাক্স ফাইলে স্বচ্ছতা জরুরি।",
    },
    "Australia": {
        "living_cost_aud_yearly": 29710,
        "estimated_solvency_bdt_lakh": 36.0,
        "solvency_summary_en": "1 year tuition + AUD $29,710 living cost + return airfare in approved bank with 3-6 months history.",
        "solvency_summary_bn": "১ বছরের টিউশন ফি + AUD $২৯,৭১০ লিভিং কস্ট + রিটার্ন বিমান ভাড়া অনুমোদিত ব্যাংকে ৩-৬ মাসের ওল্ড ফান্ড হিসেবে থাকতে হবে।",
        "work_rights": "48 hours per fortnight during study terms.",
        "study_gap_policy": "Strict Genuine Student (GS) assessment. More than 1-2 years gap without strong corporate career is heavily penalized.",
        "key_notes_en": "Immigration prioritizes Tier 1 Group of Eight universities. High rejection rate for private colleges or high study gaps.",
        "key_notes_bn": "জেনুইন স্টুডেন্ট (GS) টেস্ট অত্যন্ত কড়া। প্রাইভেট কলেজ ও দুর্বল স্পন্সরে রিজেকশনের ঝুঁকি বেশি।",
    },
    "Sweden": {
        "living_cost_sek_monthly": 10314,
        "estimated_solvency_bdt_lakh": 18.0,
        "solvency_summary_en": "Living expense of SEK 10,314/month for 10 months (SEK 103,140) + 1st installment tuition paid.",
        "solvency_summary_bn": "১০ মাসের লিভিং কস্ট (SEK ১,০৩,১৪০ বা প্রায় ১২ লাখ টাকা) এবং ১ম সেমিস্টারের টিউশন ফি পরিশোধ করতে হবে।",
        "work_rights": "No hourly legal limit during studies, but academic progression must be maintained.",
        "study_gap_policy": "Very welcoming to gaps if academic prerequisites for master's programs are met.",
        "key_notes_en": "Centralized admission via universityadmissions.se. High English proficiency standard, Schengen residence permit.",
        "key_notes_bn": "সেন্ট্রাল অ্যাডমিশন পোর্টালের মাধ্যমে আবেদন। চমৎকার স্কলারশিপ (Swedish Institute) সুবিধা রয়েছে।",
    },
    "Malaysia": {
        "estimated_solvency_bdt_lakh": 8.0,
        "solvency_summary_en": "Bank statement showing approx MYR 20,000 (~৳6-8 Lakh) for 3 months.",
        "solvency_summary_bn": "প্রায় ৬-৮ লাখ টাকার ৩ মাসের ব্যাংক স্টেটমেন্ট ও EMGS অনুমোদনপত্র প্রয়োজন।",
        "work_rights": "Restricted during semester, allowed only during semester breaks (max 20 hrs).",
        "study_gap_policy": "Very lenient on study gaps up to 5-7 years.",
        "key_notes_en": "Fast visa approval through EMGS. Dual-degree UK/Australian programs available at fraction of original cost.",
        "key_notes_bn": "EMGS এর মাধ্যমে দ্রুত ও কম ঝামেলায় ভিসা হয়। যুক্তরাজ্য বা অস্ট্রেলিয়ার ডুয়াল ডিগ্রি খুব কম খরচে অর্জন সম্ভব।",
    },
}

UNIVERSITY_CATALOG: list[dict[str, Any]] = [
    # --- GERMANY ---
    {
        "id": "de-tum",
        "name": "Technical University of Munich (TUM)",
        "country": "Germany",
        "city": "Munich",
        "world_rank_tier": "Top 50",
        "programs": ["M.Sc. Computer Science", "M.Sc. Data Engineering", "M.Sc. Power Engineering"],
        "degrees": ["bachelor", "masters"],
        "currency": "EUR",
        "annual_tuition_local": 4000.0,
        "annual_living_local": 12000.0,
        "min_gpa": 3.6,
        "min_ielts": 7.0,
        "max_study_gap": 2,
        "selectivity": "high",
        "scholarship_info": "DAAD & Deutschlandstipendium (€300/mo merit grant) eligible",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering"],
        "reasons": [
            "World-renowned engineering & CS institution",
            "High graduate employability across Europe",
            "English-taught technical master's degrees",
        ],
    },
    {
        "id": "de-rwth",
        "name": "RWTH Aachen University",
        "country": "Germany",
        "city": "Aachen",
        "world_rank_tier": "Top 150",
        "programs": ["M.Sc. Mechanical Engineering", "M.Sc. Software Systems", "M.Sc. Electrical Engineering"],
        "degrees": ["bachelor", "masters"],
        "currency": "EUR",
        "annual_tuition_local": 0.0,
        "annual_living_local": 11000.0,
        "min_gpa": 3.4,
        "min_ielts": 6.5,
        "max_study_gap": 3,
        "selectivity": "medium-high",
        "scholarship_info": "Zero tuition fee public university / NRW scholarship",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["engineering", "cs_it"],
        "reasons": [
            "Zero tuition fee (public university)",
            "Premier technical university in North Rhine-Westphalia",
            "Vibrant international student community",
        ],
    },
    {
        "id": "de-dit",
        "name": "Deggendorf Institute of Technology (DIT)",
        "country": "Germany",
        "city": "Deggendorf",
        "world_rank_tier": "Applied Sciences",
        "programs": ["B.Sc. Artificial Intelligence", "M.Sc. Applied Computer Science", "Global Public Health"],
        "degrees": ["bachelor", "masters"],
        "currency": "EUR",
        "annual_tuition_local": 1000.0,
        "annual_living_local": 9500.0,
        "min_gpa": 2.8,
        "min_ielts": 6.0,
        "max_study_gap": 4,
        "selectivity": "accessible",
        "scholarship_info": "Low tuition fee / Bavarian international performance grant",
        "accepts_moi": True,
        "coop_available": True,
        "field_tags": ["cs_it", "health"],
        "reasons": [
            "Affordable cost of living in Bavaria",
            "Practical, industry-integrated internships",
            "Friendly admission criteria for bachelor & master's applicants",
        ],
    },
    {
        "id": "de-rhine-waal",
        "name": "Rhine-Waal University of Applied Sciences",
        "country": "Germany",
        "city": "Kleve",
        "world_rank_tier": "Applied Sciences",
        "programs": ["B.Sc. Information Systems", "M.Sc. Digital Media", "B.Sc. Sustainable Agriculture"],
        "degrees": ["bachelor", "masters"],
        "currency": "EUR",
        "annual_tuition_local": 0.0,
        "annual_living_local": 9800.0,
        "min_gpa": 2.7,
        "min_ielts": 6.0,
        "max_study_gap": 4,
        "selectivity": "accessible",
        "scholarship_info": "Zero tuition fee / semester public transit pass included",
        "accepts_moi": True,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering", "business"],
        "reasons": [
            "Over 75% of bachelor and master degrees are taught 100% in English",
            "Tuition-free with free regional public transport pass included",
            "Welcoming to Bangladeshi HSC and Bachelor graduates",
        ],
    },

    # --- UNITED KINGDOM ---
    {
        "id": "uk-manchester",
        "name": "University of Manchester",
        "country": "UK",
        "city": "Manchester",
        "world_rank_tier": "Top 50 (Russell Group)",
        "programs": ["M.Sc. Advanced Computer Science", "M.Sc. Finance", "M.Sc. Biotechnology"],
        "degrees": ["bachelor", "masters"],
        "currency": "GBP",
        "annual_tuition_local": 31000.0,
        "annual_living_local": 12500.0,
        "min_gpa": 3.5,
        "min_ielts": 7.0,
        "max_study_gap": 3,
        "selectivity": "high",
        "scholarship_info": "Russell Group Global Excellence Scholarship (up to £5,000)",
        "accepts_moi": False,
        "coop_available": False,
        "field_tags": ["cs_it", "business", "health"],
        "reasons": [
            "Prestigious Russell Group university with top global brand value",
            "Exceptional campus facilities and high employer reputation",
            "Access to the UK 2-year Graduate Route Post-Study Work Visa",
        ],
    },
    {
        "id": "uk-coventry",
        "name": "Coventry University",
        "country": "UK",
        "city": "Coventry",
        "world_rank_tier": "Modern University Tier",
        "programs": ["M.Sc. Cyber Security", "M.Sc. International Business Management", "B.Eng. Automotive"],
        "degrees": ["bachelor", "masters"],
        "currency": "GBP",
        "annual_tuition_local": 18500.0,
        "annual_living_local": 10000.0,
        "min_gpa": 2.8,
        "min_ielts": 6.0,
        "max_study_gap": 5,
        "selectivity": "accessible",
        "scholarship_info": "Bangladeshi Merit Award £2,000 - £4,000 fee reduction",
        "accepts_moi": True,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering", "business"],
        "reasons": [
            "Generous merit scholarships up to £2,000 - £4,000 for Bangladeshi students",
            "Lower cost of living outside London",
            "Flexible entry criteria and recognized track record of visa approvals",
        ],
    },
    {
        "id": "uk-hertfordshire",
        "name": "University of Hertfordshire",
        "country": "UK",
        "city": "Hatfield (near London)",
        "world_rank_tier": "Modern University Tier",
        "programs": ["M.Sc. Software Engineering", "M.Sc. Data Science & Analytics", "M.Sc. Project Management"],
        "degrees": ["bachelor", "masters"],
        "currency": "GBP",
        "annual_tuition_local": 17000.0,
        "annual_living_local": 10500.0,
        "min_gpa": 2.6,
        "min_ielts": 6.0,
        "max_study_gap": 5,
        "selectivity": "accessible",
        "scholarship_info": "Chancellor's International Scholarship (£1,000 - £2,500)",
        "accepts_moi": True,
        "coop_available": True,
        "field_tags": ["cs_it", "business", "engineering"],
        "reasons": [
            "Close proximity to Central London (25 mins by train) with lower living expenses",
            "Optional 1-year professional work placement built into master's courses",
            "Reasonable initial tuition deposit requirement",
        ],
    },
    {
        "id": "uk-greenwich",
        "name": "University of Greenwich",
        "country": "UK",
        "city": "London",
        "world_rank_tier": "London Modern",
        "programs": ["M.Sc. Computer Science", "M.Sc. Global Shipping & Logistics", "MBA International"],
        "degrees": ["bachelor", "masters"],
        "currency": "GBP",
        "annual_tuition_local": 18000.0,
        "annual_living_local": 13000.0,
        "min_gpa": 2.7,
        "min_ielts": 6.0,
        "max_study_gap": 4,
        "selectivity": "accessible",
        "scholarship_info": "Early Payment Discount & International Scholarship up to £3,000",
        "accepts_moi": True,
        "coop_available": False,
        "field_tags": ["cs_it", "business"],
        "reasons": [
            "Historic campus located right inside London",
            "Flexible intake windows (September, January, April)",
            "Accepts Duolingo and Oxford ELLT for English proficiency",
        ],
    },

    # --- UNITED STATES ---
    {
        "id": "us-uta",
        "name": "University of Texas at Arlington (UTA)",
        "country": "USA",
        "city": "Arlington, TX",
        "world_rank_tier": "R1 Research",
        "programs": ["M.S. Computer Science", "M.S. Information Systems", "B.S. Civil Engineering"],
        "degrees": ["bachelor", "masters"],
        "currency": "USD",
        "annual_tuition_local": 21000.0,
        "annual_living_local": 12000.0,
        "min_gpa": 3.0,
        "min_ielts": 6.5,
        "max_study_gap": 4,
        "selectivity": "medium",
        "scholarship_info": "Competitive In-State Tuition Waiver ($10,000+/yr tuition savings)",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering"],
        "reasons": [
            "Competitive in-state tuition waiver opportunity for merit scholarship recipients",
            "Booming Dallas-Fort Worth tech corridor with extensive OPT job prospects",
            "Large, supportive Bangladeshi Student Association (BSA)",
        ],
    },
    {
        "id": "us-usf",
        "name": "University of South Florida (USF)",
        "country": "USA",
        "city": "Tampa, FL",
        "world_rank_tier": "Top 100 US Public",
        "programs": ["M.S. Business Analytics", "M.S. Cybersecurity", "B.S. Biomedical Sciences"],
        "degrees": ["bachelor", "masters"],
        "currency": "USD",
        "annual_tuition_local": 18500.0,
        "annual_living_local": 13000.0,
        "min_gpa": 3.1,
        "min_ielts": 6.5,
        "max_study_gap": 3,
        "selectivity": "medium",
        "scholarship_info": "Graduate Assistantship (GA/TA) positions with stipend & partial fee waiver",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["cs_it", "business", "health"],
        "reasons": [
            "Tier-1 research university in a rapidly growing technology & healthcare hub",
            "Warm climate and attractive graduate assistantship (GA/TA) positions",
            "High STEM-OPT 3-year post-graduation work authorization eligibility",
        ],
    },
    {
        "id": "us-sjsu",
        "name": "San Jose State University (SJSU)",
        "country": "USA",
        "city": "San Jose, CA",
        "world_rank_tier": "Silicon Valley Hub",
        "programs": ["M.S. Software Engineering", "M.S. Artificial Intelligence", "B.S. Computer Science"],
        "degrees": ["bachelor", "masters"],
        "currency": "USD",
        "annual_tuition_local": 19500.0,
        "annual_living_local": 16500.0,
        "min_gpa": 3.3,
        "min_ielts": 6.5,
        "max_study_gap": 3,
        "selectivity": "high",
        "scholarship_info": "High-paying Silicon Valley CPT/OPT industry internships ($40-$60/hr)",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering"],
        "reasons": [
            "#1 supplier of engineering talent to Silicon Valley tech giants (Apple, Google, Cisco)",
            "Unmatched networking and internship opportunities during CPT",
            "High return on investment (ROI) post graduation",
        ],
    },
    {
        "id": "us-wichita",
        "name": "Wichita State University",
        "country": "USA",
        "city": "Wichita, KS",
        "world_rank_tier": "Midwest Public",
        "programs": ["M.S. Computer Science", "M.S. Industrial Engineering", "B.B.A. Supply Chain"],
        "degrees": ["bachelor", "masters"],
        "currency": "USD",
        "annual_tuition_local": 14500.0,
        "annual_living_local": 9000.0,
        "min_gpa": 2.7,
        "min_ielts": 6.0,
        "max_study_gap": 5,
        "selectivity": "accessible",
        "scholarship_info": "Global Select Merit Scholarship ($4,800/yr automatic waiver)",
        "accepts_moi": True,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering", "business"],
        "reasons": [
            "Extremely low tuition and affordable Midwest cost of living",
            "Applied learning model with on-campus paid co-ops",
            "High visa issuance record for well-prepared applicants",
        ],
    },

    # --- CANADA ---
    {
        "id": "ca-windsor",
        "name": "University of Windsor",
        "country": "Canada",
        "city": "Windsor, ON",
        "world_rank_tier": "Comprehensive Tier",
        "programs": ["Master of Applied Computing (MAC)", "Master of Engineering (MEng)", "B.Sc. Computer Science"],
        "degrees": ["bachelor", "masters"],
        "currency": "CAD",
        "annual_tuition_local": 26000.0,
        "annual_living_local": 14000.0,
        "min_gpa": 3.0,
        "min_ielts": 6.5,
        "max_study_gap": 3,
        "selectivity": "medium",
        "scholarship_info": "Graduate Entrance Scholarship + 8-month paid industrial co-op",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering"],
        "reasons": [
            "Dedicated course-based master's with 8-month paid industrial internship",
            "Border city directly adjacent to Detroit with cross-border automotive/tech ties",
            "Eligible for full 3-year Post-Graduation Work Permit (PGWP)",
        ],
    },
    {
        "id": "ca-mun",
        "name": "Memorial University of Newfoundland (MUN)",
        "country": "Canada",
        "city": "St. John's, NL",
        "world_rank_tier": "Atlantic Canada Tier",
        "programs": ["M.Sc. Computer Science", "Master of Environmental Science", "B.Eng. Marine"],
        "degrees": ["bachelor", "masters"],
        "currency": "CAD",
        "annual_tuition_local": 13500.0,
        "annual_living_local": 11000.0,
        "min_gpa": 2.9,
        "min_ielts": 6.5,
        "max_study_gap": 4,
        "selectivity": "accessible",
        "scholarship_info": "Subsidized low government tuition & graduate research funding",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering", "health"],
        "reasons": [
            "One of the lowest tuition rates among all accredited universities in Canada",
            "Atlantic Immigration Program (AIP) provides fast-track PR pathway",
            "Strong university funding and graduate scholarships",
        ],
    },
    {
        "id": "ca-conestoga",
        "name": "Conestoga College Institute of Technology",
        "country": "Canada",
        "city": "Kitchener-Waterloo, ON",
        "world_rank_tier": "Applied College",
        "programs": ["Post-Graduate Certificate Cloud Data", "Web Development", "Supply Chain Management"],
        "degrees": ["diploma", "postgraduate_certificate"],
        "currency": "CAD",
        "annual_tuition_local": 17500.0,
        "annual_living_local": 13500.0,
        "min_gpa": 2.6,
        "min_ielts": 6.0,
        "max_study_gap": 5,
        "selectivity": "accessible",
        "scholarship_info": "International Regional Award up to $3,000 CAD",
        "accepts_moi": True,
        "coop_available": True,
        "field_tags": ["cs_it", "business", "engineering"],
        "reasons": [
            "Situated in Canada's Waterloo tech hub with direct industry co-ops",
            "Cost-effective 1-2 year fast-track career programs",
            "Pragmatic curriculum built for local Canadian labor demand",
        ],
    },

    # --- AUSTRALIA ---
    {
        "id": "au-deakin",
        "name": "Deakin University",
        "country": "Australia",
        "city": "Melbourne / Geelong, VIC",
        "world_rank_tier": "Top 250",
        "programs": ["Master of Information Technology", "Master of Data Science", "Bachelor of Nursing"],
        "degrees": ["bachelor", "masters"],
        "currency": "AUD",
        "annual_tuition_local": 36000.0,
        "annual_living_local": 24000.0,
        "min_gpa": 3.0,
        "min_ielts": 6.5,
        "max_study_gap": 2,
        "selectivity": "medium",
        "scholarship_info": "Deakin International Scholarship (up to 25% tuition fee reduction)",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["cs_it", "health"],
        "reasons": [
            "Ranked top 1% globally with state-of-the-art software engineering labs",
            "Geelong regional campus unlocks extra year of post-study work visa",
            "Up to 25% Deakin International Scholarship for good academic standing",
        ],
    },
    {
        "id": "au-wsu",
        "name": "Western Sydney University",
        "country": "Australia",
        "city": "Sydney, NSW",
        "world_rank_tier": "Top 300",
        "programs": ["Master of Information & Communications Tech", "Master of Public Health", "B.Bus."],
        "degrees": ["bachelor", "masters"],
        "currency": "AUD",
        "annual_tuition_local": 32000.0,
        "annual_living_local": 23000.0,
        "min_gpa": 2.8,
        "min_ielts": 6.5,
        "max_study_gap": 2,
        "selectivity": "accessible-medium",
        "scholarship_info": "Multi-year $3,000 - $6,000 annual scholarship for South Asian applicants",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["cs_it", "business", "health"],
        "reasons": [
            "Guaranteed multi-year $3,000 - $6,000 annual scholarships for South Asian applicants",
            "Located in the rapid economic expansion zone of Western Sydney",
            "Strong focus on industry placements and professional accreditation",
        ],
    },

    # --- SWEDEN ---
    {
        "id": "se-kth",
        "name": "KTH Royal Institute of Technology",
        "country": "Sweden",
        "city": "Stockholm",
        "world_rank_tier": "Top 80 (Nordic Top)",
        "programs": ["M.Sc. Machine Learning", "M.Sc. Software Engineering", "M.Sc. Sustainable Energy"],
        "degrees": ["masters"],
        "currency": "SEK",
        "annual_tuition_local": 160000.0,
        "annual_living_local": 115000.0,
        "min_gpa": 3.5,
        "min_ielts": 6.5,
        "max_study_gap": 4,
        "selectivity": "high",
        "scholarship_info": "Swedish Institute (SI) Full-Ride Scholarship + KTH Waiver",
        "accepts_moi": False,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering"],
        "reasons": [
            "Top technical university in Scandinavia with renowned research pedigree",
            "Stockholm is Europe's 'Unicorn capital' per capita (Spotify, Klarna, King)",
            "Eligible for Swedish Institute (SI) full-ride scholarship",
        ],
    },
    {
        "id": "se-lnu",
        "name": "Linnaeus University",
        "country": "Sweden",
        "city": "Växjö / Kalmar",
        "world_rank_tier": "Comprehensive Nordic",
        "programs": ["M.Sc. Software Technology", "M.Sc. Business Process Control", "M.Sc. Social Media Studies"],
        "degrees": ["bachelor", "masters"],
        "currency": "SEK",
        "annual_tuition_local": 135000.0,
        "annual_living_local": 100000.0,
        "min_gpa": 2.9,
        "min_ielts": 6.5,
        "max_study_gap": 5,
        "selectivity": "accessible",
        "scholarship_info": "Linnaeus University Scholarship (up to 75% tuition discount)",
        "accepts_moi": False,
        "coop_available": False,
        "field_tags": ["cs_it", "business"],
        "reasons": [
            "Friendly admission requirements and high graduate satisfaction",
            "Affordable cost of living compared to Stockholm/Gothenburg",
            "Welcoming to Bangladeshi students with clear, transparent application portal",
        ],
    },

    # --- MALAYSIA ---
    {
        "id": "my-apu",
        "name": "Asia Pacific University of Technology & Innovation (APU)",
        "country": "Malaysia",
        "city": "Kuala Lumpur",
        "world_rank_tier": "Tech Specialist Tier",
        "programs": ["B.Sc. Cyber Security", "M.Sc. Data Science", "B.Sc. Software Engineering"],
        "degrees": ["bachelor", "masters"],
        "currency": "MYR",
        "annual_tuition_local": 36000.0,
        "annual_living_local": 20000.0,
        "min_gpa": 2.5,
        "min_ielts": 5.5,
        "max_study_gap": 6,
        "selectivity": "accessible",
        "scholarship_info": "Merit-based tuition waiver up to 30% for GPA > 3.5",
        "accepts_moi": True,
        "coop_available": True,
        "field_tags": ["cs_it", "engineering"],
        "reasons": [
            "Dual-degree certification option with De Montfort University (UK)",
            "Ultra-modern technology campus with 100% employability track record",
            "Very affordable overall cost: ~৳12-15 Lakh/year all-inclusive",
        ],
    },
    {
        "id": "my-taylors",
        "name": "Taylor's University",
        "country": "Malaysia",
        "city": "Subang Jaya",
        "world_rank_tier": "Top 300 Global (#1 Private in SE Asia)",
        "programs": ["Bachelor of Computer Science", "Master of Management", "Bachelor of Architecture"],
        "degrees": ["bachelor", "masters"],
        "currency": "MYR",
        "annual_tuition_local": 42000.0,
        "annual_living_local": 22000.0,
        "min_gpa": 2.7,
        "min_ielts": 6.0,
        "max_study_gap": 5,
        "selectivity": "accessible",
        "scholarship_info": "Taylor's International Excellence Award (up to 50% waiver)",
        "accepts_moi": True,
        "coop_available": True,
        "field_tags": ["cs_it", "business"],
        "reasons": [
            "Ranked the #1 private university in Southeast Asia",
            "World-class lakeside campus with excellent internship programs",
            "Fast-track student visa processing via EMGS (4-6 weeks typical)",
        ],
    },
]


def convert_to_bdt_lakh(amount_local: float, currency: str) -> float:
    """Converts a local currency amount to BDT in Lakhs (1 Lakh = 100,000 BDT)."""
    rate = CURRENCY_RATES_TO_BDT.get(currency.upper(), 120.0)
    total_bdt = amount_local * rate
    return round(total_bdt / 100000.0, 2)
